{app_criteria: wage, aspiration_offset: 0, aspiration_var: 0.2, base_fertility_a: 1.2,
  base_fertility_b: 3.0, base_fertility_c: 26, churn: 0.025, cohort_width: 5.0, default_aspiration: 0.3,
  desire2: 0.5, exp_max: 10, experience_floor: false, fecundity_a: 1, fecundity_b: 0.02,
  fecundity_c: 0.0015, fecundity_mu: 25, feedback_mult: 1.0, female_weight_in_threshold: 0,
  fertility_type: prob_easterlin, further_fertility_a: 0.4, further_fertility_b: 0.1,
  further_fertility_mu: 2.5, gompertz_a: 0.001, gompertz_b: 0.085, gompertz_l: 0.0,
  gompertz_start: 30, growth_rate: 0.0, imprinting_time: 15, inheritance: true, inheritance_corr: 0.5,
  initial_aspiration_max: 1.5, job_apps_employed: 3.0, job_apps_unemployed: 15.0,
  job_burnin_rounds: 5, job_upper_limit: 999999, linear_growth: 0.0, log_wages: false,
  parity_feedback_mult: 1.0, parity_offset: 0.2, partner_age_diff: 3, partnering_a: 1.2,
  partnering_alpha: 0.2, partnering_lambda: 0.3, partnering_mu: 21, pop_size: 5000,
  prob_asymptote: 0.5, prob_mult: 1.0, prod_type: difficulty, prop_male_at_birth: 0.5,
  retirement_age: 65, setup_job_lab_ratio: 0.9, setup_marriage_age_a: -1, setup_marriage_age_b: 0.25,
  setup_marriage_age_mid: 20, social_security_level: 0.05, start_date: '1900-01-01',
  starting_hump_mult: 1.0, starting_hump_peak: 50.0, support_ratio: 3.0, timestep: year,
  wage_alpha: 1.0, wage_beta: 1.0, wage_delta: 0.0003, wage_feedback_mult: 1.0, wage_gamma: 0.025,
  wage_nu: 0.25, year_length: 365.0}
